// 不需要验证 token 的接口路径列表
// 直接写路径（与 req.path 完全匹配）
export default [
  '/login',
  '/refreshToken',
  '/logout',
  '/insertUser',
  '/isRegister',
  '/verify',
  '/visits',
  '/survey',
  '/recordVisit',
  '/banner',
  '/article',
  '/gainArticle',
  '/addPraise',
  '/deletePraise',
  '/subset',
  '/gainSubset',
  '/getcomment',
  '/likecomment',
  '/addcomment',
  '/deletelikecomment',
  '/diary',
  '/gainDiary',
  '/gainDiaryDate',
  '/sendMessage',
  '/resource',
  '/downloadresource',
  '/reportcomment',
]
